services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - certbot
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs/:/var/log/nginx/
      - ./certbot/conf/:/etc/letsencrypt/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    environment:
      - DOMAIN=${CERTBOT_DOMAIN}
    networks:
      - local-network

  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
    container_name: certbot
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      CERTBOT_DOMAIN: ${CERTBOT_DOMAIN}
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/logs:/var/log/letsencrypt/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local-network
    

  helloworld:
    image: crccheck/hello-world
    container_name: helloworld
    ports:
      - 3000:8000
    networks:
      - local-network


networks:
  local-network:
    driver: bridge